apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-manager
  namespace: unlok
spec:
  project: unlok
  source:
    repoURL: https://github.com/uday1921/K8s-test.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: unlok/app1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
