apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow-dev-manager
  namespace: argocd
spec:
  project: unlok
  source:
    repoURL: https://github.com/uday1921/K8s-test.git
    targetRevision: develop
    path: unlok/app3
  destination:
    server: https://kubernetes.default.svc
    namespace: develop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
